# Generated by Django 3.1.4 on 2021-03-30 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(upload_to='uploads/menu')),
                ('price', models.IntegerField(default=20)),
                ('discount', models.IntegerField(default=0)),
            ],
        ),
    ]
